
POST http://localhost:4000/src/auth/authen/register HTTP/1.1
Content-Type: application/json

{
    "username": "thong",
    "password": "aaaa4444",
    "role":"admin"

}

# {
#     "username": "aek",
#     "password": "aaaa4444",
#     "role":"admin"

# }

###

POST   HTTP/1.1
Content-Type: application/json

{
    "username": "aek",
    "password": "aaaa4444"

}
###
GET http://localhost:4000/src/auth/authen/profile HTTP/1.1
Content-Type: application/json

{
    "username": "test",
    "password": "1234567"

}
