### ລາຍງານເຈັບປິ່ນປົວ ຕໍ່ຄົນ
# http://localhost:4000/src/report/patient/:id
GET http://localhost:4000/src/report/patient/AA1234 HTTP/1.1
Content-Type: application/json

### ລາຍການປິ່ນປົ່ວ ຕໍ່ຄົນ
# http://localhost:4000/src/report/inspection/:id
GET http://localhost:4000/src/report/inspection/PT200625212916 HTTP/1.1
Content-Type: application/json


### ລາຍການຈ່າຍຢາ ຕໍ່ຄົນ
# http://localhost:4000/src/report/prescription/:id
GET http://localhost:4000/src/report/prescription/PT220625002405 HTTP/1.1
Content-Type: application/json


### ຕາຕະລາງການປິ່ນປົວ
GET http://localhost:4000/src/report/inspection HTTP/1.1
Content-Type: application/json

### ຈຳນວນຢາທີ່ຈ່າຍໄປ
GET http://localhost:4000/src/report/prescription HTTP/1.1
Content-Type: application/json

### ຈຳນວນຢາຍັງເຫລືອ
GET http://localhost:4000/src/report/stock HTTP/1.1
Content-Type: application/json
### 
GET http://localhost:4000/src/report/payment HTTP/1.1
Content-Type: application/json

### 

GET http://localhost:4000/src/report/import HTTP/1.1
Content-Type: application/json

##